version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - $DEV_POSTGRES_PORT
    environment:
      - POSTGRES_USER=$DEV_POSTGRES_USER
      - POSTGRES_PASSWORD=$DEV_POSTGRES_PASSWORD
      - POSTGRES_DB=$DEV_POSTGRES_DATABASE
